### ISSUE TITLE
Backup & Upgrade Ko on bookworm

### ISSUE THREAD

**Issue by nathanael-h** [YunoHost-Apps/monitorix_ynh#66] opened 2024-08-23 07:04 UTC
Hello, 
I upgraded to Bookworm and face an issue when trying to upgrade Monitorix: the safety backup is KO, thus the upgrade cannot be done. 

Here are the logs https://paste.yunohost.org/raw/izotixoban

Relevant parts are 
```
1017 DEBUG   Executing command '['sh', '-c', '/bin/bash -x "/var/cache/yunohost/app_tmp_work_dirs/app_a_yflttz/scripts/backup"  7>&1']'
1018 DEBUG   illegal environment variable name
```

```
yunohost tools versions 

yunohost: 
  repo: testing
  version: 12.0.2
yunohost-admin: 
  repo: testing
  version: 12.0.1
moulinette: 
  repo: testing
  version: 12.0.1
ssowat: 
  repo: testing
  version: 12.0.1

```

**Comment by nathanael-h** [comment] 2024-08-23 07:09
I also run the upgrade without the safety backup and it failed. Here are the logs https://paste.yunohost.org/raw/suzodibuge

**Comment by Josue-T** [comment] 2024-08-23 16:47
Maybe the solution would be to remove all `previous_*` key in `/etc/yunohost/apps/monitorix/settings.yml`.

And after try an upgrade (without backup).

**Comment by olberger** [comment] 2024-08-27 09:16
Btw, this is not specifically related to upgrading YNH to bookworm AFAICT, since I get also a similar error by just trying to update Monitorix from 3.15.0~ynh7 to 3.15.0~ynh8, on YNH 11.2.28 (stable)

See https://paste.yunohost.org/raw/uginidekin for details

**Comment by olberger** [comment] 2024-08-27 09:20
Hmmm... regarding your suggestion, @Josue-T 
> Maybe the solution would be to remove all `previous_*` key in `/etc/yunohost/apps/monitorix/settings.yml`.
> 
> And after try an upgrade (without backup).

Would this apply to just updating Monitorix, still on YNH 11 ?

**Comment by Josue-T** [comment] 2024-08-27 15:48
> Hmmm... regarding your suggestion, @Josue-T
> 
> > Maybe the solution would be to remove all `previous_*` key in `/etc/yunohost/apps/monitorix/settings.yml`.
> > And after try an upgrade (without backup).
> 
> Would this apply to just updating Monitorix, still on YNH 11 ?

Yes, this should solve all issues related to the upgrade.

**Comment by olberger** [comment] 2024-08-29 07:23
Btw, I just noticed:
```
ls -l /etc/yunohost/apps/monitorix/settings.yml
-r-------- 1 root root 3587 Aug  6 09:04 /etc/yunohost/apps/monitorix/settings.yml
```
I find it rather strange that the file isn't writable by root, but... I can force writing anyway... just wondering if it's by design or something fishy...

**Comment by Josue-T** [comment] 2024-08-29 20:42
Hello,

So, the issue come from a key (in `/etc/yunohost/apps/monitorix/settings.yml`) which is not compatible with a environment variable name. And I had this isssue some time ago and I solved by removing all  `previous_*` key in `/etc/yunohost/apps/monitorix/settings.yml` (note you can safely remove theses key/value as it's only used for optimization of the hook and it's automatically regenerated after the next run). I don't remember exactly the cause but I'm quite sure that it was solved (as it's a big issue and not easy to fix).

So can you share the result of this command `cat /etc/yunohost/apps/monitorix/settings.yml  | cut -d: -f1` so I can see the problematic key and than suggest a more specific fix.

**Comment by MadMan247** [comment] 2024-09-02 18:23
https://paste.yunohost.org/raw/ziyesufacu

Can confirm, not exclusive to bookworm

YNH 11.2.30

**Comment by olberger** [comment] 2024-09-06 06:38
Same as @ MadMan247 for me when going in the app's page :
> Also, in webadmin > applications > monitorix: [Unexpected server error]

It seems that `/api/apps/monitorix/config?full&locale=en` spits:
``` json
{
  "route": [
    "GET",
    "/apps/<app>/config"
  ],
  "arguments": {
    "app": "monitorix",
    "full": ""
  },
  "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/moulinette/interfaces/api.py\", line 450, in process\n    ret = self.actionsmap.process(arguments, timeout=30, route=_route)\n  File \"/usr/lib/python3/dist-packages/moulinette/actionsmap.py\", line 574, in process\n    return func(**arguments)\n  File \"/usr/lib/python3/dist-packages/yunohost/app.py\", line 1915, in app_config_get\n    return config_.get(key, mode)\n  File \"/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py\", line 116, in get\n    self._get_raw_settings()\n  File \"/usr/lib/python3/dist-packages/yunohost/app.py\", line 1947, in _get_raw_settings\n    self.values = self._call_config_script(\"show\")\n  File \"/usr/lib/python3/dist-packages/yunohost/app.py\", line 2010, in _call_config_script\n    ret, values = hook_exec(config_script, args=[action], env=env)\n  File \"/usr/lib/python3/dist-packages/yunohost/hook.py\", line 404, in hook_exec\n    returncode, returndata = _hook_exec_bash(\n  File \"/usr/lib/python3/dist-packages/yunohost/hook.py\", line 471, in _hook_exec_bash\n    returncode = call_async_output(command, loggers, shell=False, cwd=chdir, env=_env)\n  File \"/usr/lib/python3/dist-packages/moulinette/utils/process.py\", line 80, in call_async_output\n    p = subprocess.Popen(args, **kwargs)\n  File \"/usr/lib/python3.9/subprocess.py\", line 951, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n  File \"/usr/lib/python3.9/subprocess.py\", line 1742, in _execute_child\n    raise ValueError(\"illegal environment variable name\")\nValueError: illegal environment variable name\n"
}
```
The stack trace, in clear:
```
Traceback (most recent call last):
  File \"/usr/lib/python3/dist-packages/moulinette/interfaces/api.py\", line 450, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File \"/usr/lib/python3/dist-packages/moulinette/actionsmap.py\", line 574, in process
    return func(**arguments)
  File \"/usr/lib/python3/dist-packages/yunohost/app.py\", line 1915, in app_config_get
    return config_.get(key, mode)
  File \"/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py\", line 116, in get
    self._get_raw_settings()
  File \"/usr/lib/python3/dist-packages/yunohost/app.py\", line 1947, in _get_raw_settings
    self.values = self._call_config_script(\"show\")
  File \"/usr/lib/python3/dist-packages/yunohost/app.py\", line 2010, in _call_config_script
    ret, values = hook_exec(config_script, args=[action], env=env)
  File \"/usr/lib/python3/dist-packages/yunohost/hook.py\", line 404, in hook_exec
    returncode, returndata = _hook_exec_bash(
  File \"/usr/lib/python3/dist-packages/yunohost/hook.py\", line 471, in _hook_exec_bash
    returncode = call_async_output(command, loggers, shell=False, cwd=chdir, env=_env)
  File \"/usr/lib/python3/dist-packages/moulinette/utils/process.py\", line 80, in call_async_output
    p = subprocess.Popen(args, **kwargs)
  File \"/usr/lib/python3.9/subprocess.py\", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File \"/usr/lib/python3.9/subprocess.py\", line 1742, in _execute_child
    raise ValueError(\"illegal environment variable name\")
ValueError: illegal environment variable name
```

**Comment by olberger** [comment] 2024-09-06 06:43
> So, the issue come from a key (in `/etc/yunohost/apps/monitorix/settings.yml`) which is not compatible with a environment variable name. And I had this isssue some time ago and I solved by removing all `previous_*` key in `/etc/yunohost/apps/monitorix/settings.yml` (note you can safely remove theses key/value as it's only used for optimization of the hook and it's automatically regenerated after the next run). 

Which hook is it, more specifically ? (seems also the same cause as the error reported above, in a hook script...

Thanks for these useful details.

**Comment by olberger** [comment] 2024-09-06 07:17
Hi @MadMan247 .
I had a similar content, and I think the problem lies in the `checksum_--file` value, which doesn't look very clean, compared to other checksum vars:
> the CAT command that you provided (had to be sudo)
> 
> ```
> checksum_--file=_etc_monitorix_monitorix.conf
> checksum_--file=_etc_nginx_conf.d_monitorix_status.conf
> checksum__etc_monitorix_monitorix.conf
> checksum__etc_nginx_conf.d_host.edsmcserv.com.d_monitorix.conf
> checksum__etc_nginx_conf.d_monitorix_status.conf
> checksum__etc_php_7.4_fpm_pool.d_monitorix_status.conf
> checksum__etc_php_8.0_fpm_pool.d_monitorix_status.conf
> checksum__etc_php_8.1_fpm_pool.d_monitorix_status.conf
> checksum__etc_php_8.2_fpm_pool.d_monitorix_status.conf
> checksum__etc_php_8.3_fpm_pool.d_monitorix_status.conf
> checksum__etc_systemd_system_monitorix.service
> checksum__opt_yunohost_monitorix_monitorix-alert.sh

I changed liked this and it seems much better now:
``` diff
# diff /etc/yunohost/apps/monitorix/settings.yml.old /etc/yunohost/apps/monitorix/settings.yml
3,4c3,4
< checksum_--file=_etc_monitorix_monitorix.conf: ''
< checksum_--file=_etc_nginx_conf.d_monitorix_status.conf: ''
---
> checksum__etc_monitorix_monitorix.conf: ''
> checksum__etc_nginx_conf.d_monitorix_status.conf: ''
```

**Comment by olberger** [comment] 2024-09-06 07:51
Yeah, after fixing these `checksum_--file=` erronous values in `/etc/yunohost/apps/monitorix/settings.yml`, the upgrade was succesful :-)

FWIW:
``` diff
# diff /etc/yunohost/apps/monitorix/settings.yml.old /etc/yunohost/apps/monitorix/settings.yml
3,6c3,4
< checksum_--file=_etc_monitorix_monitorix.conf: ''
< checksum_--file=_etc_nginx_conf.d_monitorix_status.conf: ''
< checksum__etc_monitorix_monitorix.conf: 62553f1f1d264263fbb25c023cdbb4ce
< checksum__etc_nginx_conf.d_monitorix_status.conf: 46b37f61f8c2aa7f3cebe796c2d8bb90
---
> checksum__etc_monitorix_monitorix.conf: 3302b5cf83ab81525d14106deda2ef8c
> checksum__etc_nginx_conf.d_monitorix_status.conf: 663497695afb25a20903ea7b028c782e
8,11c6,9
< checksum__etc_php_7.4_fpm_pool.d_monitorix_status.conf: cc9067c2ee470dc248b14b194209a34e
< checksum__etc_php_8.1_fpm_pool.d_monitorix_status.conf: 4148b6e17ce071b4ff5cbb6bae940d5f
< checksum__etc_php_8.2_fpm_pool.d_monitorix_status.conf: 96650556dbee2a0aad9b892dd8792c5a
< checksum__etc_php_8.3_fpm_pool.d_monitorix_status.conf: 63c2922be615766fae3374d0e4fa8058
---
> checksum__etc_php_7.4_fpm_pool.d_monitorix_status.conf: 6d93d3216dc4a7f5df47d4876fbec4d3
> checksum__etc_php_8.1_fpm_pool.d_monitorix_status.conf: 86a21c26fb3b77b16dde505c87214b8e
> checksum__etc_php_8.2_fpm_pool.d_monitorix_status.conf: b6e754578c2c064e4854381906f04d19
> checksum__etc_php_8.3_fpm_pool.d_monitorix_status.conf: 7919280bcbc96e5fb156d18bd65a70e1
14c12
< current_revision: 2714ce14232c64ff7a10a877fa1bb03ea28bb295
---
> current_revision: 7c45b5268c0ab2dedb92ebb0430e0aad84320d0f
92c90
< previous_mysql_installed: 'false'
---
> previous_mysql_installed: 'true'
139c137
< update_time: 1717097717
---
> update_time: 1725607637
```

**Comment by Josue-T** [comment] 2024-10-12 19:59
Closing as the solution is documented and the issue should not happen again.

**Closed** 2024-10-12 19:59 UTC
Labels: bug
